const {chromium}=require('playwright');const assert=require('node:assert/strict');
const base=process.env.BASE_URL||'http://127.0.0.1:18941';
(async()=>{const b=await chromium.launch({args:['--no-sandbox']});
const ctx=await b.newContext({javaScriptEnabled:false});const p=await ctx.newPage();
for(const [path,lang,heading]of [['/','en','Backend engineering.'],['/en/','en','Backend engineering.'],['/zh-hant/','zh-Hant','專注後端，'],['/zh-hans/','zh-Hans','专注后端，']]){
 const r=await p.goto(base+path);assert.equal(r.status(),200);assert.equal(await p.locator('html').getAttribute('lang'),lang);assert((await p.locator('h1').innerText()).includes(heading));assert.equal(await p.locator('link[rel=canonical]').getAttribute('href'),'https://wayneclub.com'+path);assert.equal(await p.locator('link[hreflang]').count(),4);assert.equal(await p.locator('a[href="mailto:me@wayneclub.com"]').count(),2);assert(await p.locator('script[type="application/ld+json"]').evaluate(el=>JSON.parse(el.textContent)['@graph'][2].email==='me@wayneclub.com'));assert.equal(r.headers()['x-content-type-options'],'nosniff');assert.match(r.headers()['content-security-policy'],/object-src 'none'/);assert(!r.headers()['content-security-policy'].includes("script-src 'self' 'unsafe-inline'"));
 console.log('PASS no-JS localized SEO + headers',path);
}
for(const path of ['/robots.txt','/sitemap.xml','/llms.txt','/assets/wayne-club-social.png'])assert.equal((await p.request.get(base+path)).status(),200);
for(const method of ['POST','PUT','DELETE','PATCH'])assert.equal((await p.request.fetch(base+'/',{method})).status(),405);
for(const path of ['/.env','/.git/config','/wp-login.php','/api/contact'])assert.equal((await p.request.get(base+path)).status(),404);
await ctx.close();
const c=await b.newContext({locale:'zh-TW',viewport:{width:390,height:844}});const page=await c.newPage();const requests=[];const errors=[];page.on('request',r=>{if(/google-analytics|googletagmanager/.test(r.url()))requests.push(r.url())});page.on('pageerror',e=>errors.push(e.message));
await page.route('https://www.googletagmanager.com/**',r=>r.fulfill({status:200,body:'/* mocked only for consent unit behavior */',contentType:'text/javascript'}));
await page.goto(base+'/?email=private@example.com#secret',{waitUntil:'networkidle'});assert.equal(requests.length,0);await page.locator('[data-consent=denied]').click();assert.equal(requests.length,0);await page.locator('.privacy-button').click();await Promise.all([page.waitForRequest(r=>r.url().includes('googletagmanager.com/gtag/js')),page.locator('#analytics-select').selectOption('granted')]);assert.equal(requests.length,1);const events=await page.evaluate(()=>dataLayer.map(x=>Array.from(x)));assert(events.some(x=>x[0]==='event'&&x[1]==='page_view'));assert(!JSON.stringify(events).includes('private@example.com'));assert(!JSON.stringify(events).includes('#secret'));await page.locator('#analytics-select').selectOption('denied');assert(await page.evaluate(()=>window['ga-disable-G-TV15PT58R3']));await page.keyboard.press('Escape');await page.reload({waitUntil:'networkidle'});assert.equal(requests.length,1);assert.deepEqual(errors,[]);
await page.goto(base+'/zh-hans/',{waitUntil:'networkidle'});assert.equal(await page.locator('html').getAttribute('lang'),'zh-Hans');await page.locator('.settings-button').click();await page.locator('#language-select').selectOption('en');assert.equal(new URL(page.url()).pathname,'/en/');assert((await page.locator('h1').innerText()).includes('Backend engineering.'));await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('html').getAttribute('lang'),'en');console.log('PASS consent gating, withdrawal, PII stripping, stable locale URLs');await c.close();
const attack=await b.newContext();const a=await attack.newPage();await a.goto(base+'/?q=%3Cscript%3Ewindow.injected%3Dtrue%3C%2Fscript%3E',{waitUntil:'networkidle'});assert(!(await a.evaluate(()=>window.injected)));assert(!(await a.locator('body').innerText()).includes('window.injected'));await a.evaluate(()=>{const s=document.createElement('script');s.textContent='window.inlineInjected=true';document.body.append(s)});assert(!(await a.evaluate(()=>window.inlineInjected)));console.log('PASS query is not reflected + CSP blocks inline execution');await attack.close();await b.close()})().catch(e=>{console.error(e);process.exit(1)});
